export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const CONFIRM_ACCESS = 'CONFIRM_ACCESS';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';


export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const SEND_PASSWORD_RESET_TOKEN = 'SEND_PASSWORD_RESET_TOKEN';
export const RESET_MEMBER_PASSWORD = 'RESET_MEMBER_PASSWORD';

// Used By Auth
export const LOAD_CURRENT_MEMBER = 'LOAD_CURRENT_MEMBER';

export const LOAD_MEMBER_PROFILE = 'LOAD_MEMBER_PROFILE';
export const CREATE_MEMBER_PROFILE = 'CREATE_MEMBER_PROFILE';
export const UPDATE_MEMBER_IMAGE = 'UPDATE_MEMBER_IMAGE';
export const UPDATE_MEMBER_PROFILE = 'UPDATE_MEMBER_PROFILE';
export const UPDATE_AUTH_DATA = 'UPDATE_AUTH_DATA';
export const UPDATE_UNIT_INFO = 'UPDATE_UNIT_INFO';
export const UPDATE_CHURCH_INFO = 'UPDATE_CHURCH_INFO';
export const UPDATE_NOK_INFO = 'UPDATE_NOK_INFO';
export const DELETE_PROFILE = 'DELETE_PROFILE';

// export const DELETE_CURRENT_MEMBER_PROFILE = 'DELETE_CURRENT_MEMBER_PROFILE';

// Admin
export const LOAD_MEMBERS = 'LOAD_MEMBERS';
export const GET_MEMBER_PROFILE = 'GET_MEMBER_PROFILE';
export const CLEAR_MEMBER_PROFILE = 'CLEAR_MEMBER_PROFILE';

export const GENERATE_REPORT = 'GENERATE_REPORT';
export const BECOME_ADMIN = 'BECOME_ADMIN';
export const TOGGLE_ADMIN_AUTH = 'TOGGLE_ADMIN_AUTH';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const FLUSH_DATA = 'FLUSH_DATA';

