export const baseURL = process.env.NODE_ENV === 'production' ? 'https://ft-choir-portal.herokuapp.com' : 'http://localhost:5000';

/********SHILOH */
export const SHILOH_SIGNUP = 'SHILOH_SIGNUP';
export const GET_SHILOH_DATA = 'GET_SHILOH_DATA';
export const UPDATE_SHILOH_DATA = 'UPDATE_SHILOH_DATA';
export const DELETE_SHILOH_DATA = 'DELETE_SHILOH_DATA';
export const RESET_SHILOH_DATA = 'RESET_SHILOH_DATA';
export const GET_SHILOH_ATTENDANCE_LIST = 'GET_SHILOH_ATTENDANCE_LIST';
export const GENERATE_SHILOH_ATTENDANCE_REPORT = 'GENERATE_SHILOH_ATTENDANCE_REPORT';

/******** ALERT  */
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const CONFIRM_ACCESS = 'CONFIRM_ACCESS';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';


export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const SEND_PASSWORD_RESET_TOKEN = 'SEND_PASSWORD_RESET_TOKEN';
export const RESET_MEMBER_PASSWORD = 'RESET_MEMBER_PASSWORD';

// Used By Auth
export const LOAD_CURRENT_MEMBER = 'LOAD_CURRENT_MEMBER';

export const LOAD_MEMBER_PROFILE = 'LOAD_MEMBER_PROFILE';
export const CREATE_MEMBER_PROFILE = 'CREATE_MEMBER_PROFILE';
export const UPDATE_MEMBER_IMAGE = 'UPDATE_MEMBER_IMAGE';
export const UPDATE_MEMBER_PROFILE = 'UPDATE_MEMBER_PROFILE';
export const UPDATE_AUTH_DATA = 'UPDATE_AUTH_DATA';
export const UPDATE_UNIT_INFO = 'UPDATE_UNIT_INFO';
export const UPDATE_CHURCH_INFO = 'UPDATE_CHURCH_INFO';
export const UPDATE_NOK_INFO = 'UPDATE_NOK_INFO';
export const DELETE_PROFILE = 'DELETE_PROFILE';

// Posts
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const SET_POST_BY_POST_ID = 'SET_POST_BY_POST_ID';
export const NEW_POST_CREATED = 'NEW_POST_CREATED';
export const POST_DELETED = 'POST_DELETED';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';
export const REMOVE_POST_COMMENT = 'REMOVE_POST_COMMENT';


// Admin
export const GET_ACCESS = 'GET_ACCESS';
export const UPLOAD_ACCESS = 'UPLOAD_ACCESS';
export const ADD_ACCESS = 'ADD_ACCESS';
export const DELETE_ACCESS = 'DELETE_ACCESS';
export const FLUSH_ACCESS_LIST = 'FLUSH_ACCESS_LIST';
export const CLEAR_ACCESS_LIST = 'CLEAR_ACCESS_LIST';
export const RESET_ACCESS_DATA = 'RESET_ACCESS_DATA';

export const LOAD_MEMBERS = 'LOAD_MEMBERS';
export const GET_MEMBER_PROFILE = 'GET_MEMBER_PROFILE';
export const CLEAR_MEMBER_PROFILE = 'CLEAR_MEMBER_PROFILE';

export const GENERATE_REPORT = 'GENERATE_REPORT';
export const BECOME_ADMIN = 'BECOME_ADMIN';
export const TOGGLE_ADMIN_AUTH = 'TOGGLE_ADMIN_AUTH';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const FLUSH_DATA = 'FLUSH_DATA';



